// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: swipe.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const newSwipe = `-- name: NewSwipe :exec
INSERT INTO swipes (swiper_id, swipee_id) VALUES(
    $1, $2 -- Swiper ID and Swipee ID
) ON CONFLICT (swiper_id, swipee_id) DO NOTHING
`

type NewSwipeParams struct {
	SwiperID pgtype.UUID `json:"swiper_id"`
	SwipeeID pgtype.UUID `json:"swipee_id"`
}

// Handle swipes
func (q *Queries) NewSwipe(ctx context.Context, arg NewSwipeParams) error {
	_, err := q.db.Exec(ctx, newSwipe, arg.SwiperID, arg.SwipeeID)
	return err
}
